// Generated by view binder compiler. Do not edit!
package com.rasika.nurturenectar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import com.rasika.nurturenectar.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySigninBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button btnRegister;

  @NonNull
  public final TextInputLayout etEmail;

  @NonNull
  public final TextInputEditText etEmailValue;

  @NonNull
  public final TextInputLayout etFullname;

  @NonNull
  public final TextInputEditText etFullnameValue;

  @NonNull
  public final TextInputEditText etPasdsowrdValue;

  @NonNull
  public final TextInputEditText etPassConfirmValue;

  @NonNull
  public final TextInputLayout etPassword;

  @NonNull
  public final TextInputLayout etpassConfirm;

  @NonNull
  public final TextView textView4;

  @NonNull
  public final TextView textViewLogin;

  @NonNull
  public final TextView textviewDec;

  private ActivitySigninBinding(@NonNull ConstraintLayout rootView, @NonNull Button btnRegister,
      @NonNull TextInputLayout etEmail, @NonNull TextInputEditText etEmailValue,
      @NonNull TextInputLayout etFullname, @NonNull TextInputEditText etFullnameValue,
      @NonNull TextInputEditText etPasdsowrdValue, @NonNull TextInputEditText etPassConfirmValue,
      @NonNull TextInputLayout etPassword, @NonNull TextInputLayout etpassConfirm,
      @NonNull TextView textView4, @NonNull TextView textViewLogin, @NonNull TextView textviewDec) {
    this.rootView = rootView;
    this.btnRegister = btnRegister;
    this.etEmail = etEmail;
    this.etEmailValue = etEmailValue;
    this.etFullname = etFullname;
    this.etFullnameValue = etFullnameValue;
    this.etPasdsowrdValue = etPasdsowrdValue;
    this.etPassConfirmValue = etPassConfirmValue;
    this.etPassword = etPassword;
    this.etpassConfirm = etpassConfirm;
    this.textView4 = textView4;
    this.textViewLogin = textViewLogin;
    this.textviewDec = textviewDec;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySigninBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySigninBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_signin, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySigninBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnRegister;
      Button btnRegister = ViewBindings.findChildViewById(rootView, id);
      if (btnRegister == null) {
        break missingId;
      }

      id = R.id.etEmail;
      TextInputLayout etEmail = ViewBindings.findChildViewById(rootView, id);
      if (etEmail == null) {
        break missingId;
      }

      id = R.id.etEmailValue;
      TextInputEditText etEmailValue = ViewBindings.findChildViewById(rootView, id);
      if (etEmailValue == null) {
        break missingId;
      }

      id = R.id.etFullname;
      TextInputLayout etFullname = ViewBindings.findChildViewById(rootView, id);
      if (etFullname == null) {
        break missingId;
      }

      id = R.id.etFullnameValue;
      TextInputEditText etFullnameValue = ViewBindings.findChildViewById(rootView, id);
      if (etFullnameValue == null) {
        break missingId;
      }

      id = R.id.etPasdsowrdValue;
      TextInputEditText etPasdsowrdValue = ViewBindings.findChildViewById(rootView, id);
      if (etPasdsowrdValue == null) {
        break missingId;
      }

      id = R.id.etPassConfirmValue;
      TextInputEditText etPassConfirmValue = ViewBindings.findChildViewById(rootView, id);
      if (etPassConfirmValue == null) {
        break missingId;
      }

      id = R.id.etPassword;
      TextInputLayout etPassword = ViewBindings.findChildViewById(rootView, id);
      if (etPassword == null) {
        break missingId;
      }

      id = R.id.etpassConfirm;
      TextInputLayout etpassConfirm = ViewBindings.findChildViewById(rootView, id);
      if (etpassConfirm == null) {
        break missingId;
      }

      id = R.id.textView4;
      TextView textView4 = ViewBindings.findChildViewById(rootView, id);
      if (textView4 == null) {
        break missingId;
      }

      id = R.id.textViewLogin;
      TextView textViewLogin = ViewBindings.findChildViewById(rootView, id);
      if (textViewLogin == null) {
        break missingId;
      }

      id = R.id.textviewDec;
      TextView textviewDec = ViewBindings.findChildViewById(rootView, id);
      if (textviewDec == null) {
        break missingId;
      }

      return new ActivitySigninBinding((ConstraintLayout) rootView, btnRegister, etEmail,
          etEmailValue, etFullname, etFullnameValue, etPasdsowrdValue, etPassConfirmValue,
          etPassword, etpassConfirm, textView4, textViewLogin, textviewDec);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
