// Generated by view binder compiler. Do not edit!
package com.rasika.nurturenectar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import com.rasika.nurturenectar.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityLoginBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button buttonLogin;

  @NonNull
  public final TextInputLayout etEmail;

  @NonNull
  public final TextInputEditText etEmailValue;

  @NonNull
  public final TextInputEditText etPassValue;

  @NonNull
  public final TextInputLayout etpass;

  @NonNull
  public final ImageView imageViewSource;

  @NonNull
  public final TextView textView3;

  @NonNull
  public final TextView textViewSigin;

  private ActivityLoginBinding(@NonNull ConstraintLayout rootView, @NonNull Button buttonLogin,
      @NonNull TextInputLayout etEmail, @NonNull TextInputEditText etEmailValue,
      @NonNull TextInputEditText etPassValue, @NonNull TextInputLayout etpass,
      @NonNull ImageView imageViewSource, @NonNull TextView textView3,
      @NonNull TextView textViewSigin) {
    this.rootView = rootView;
    this.buttonLogin = buttonLogin;
    this.etEmail = etEmail;
    this.etEmailValue = etEmailValue;
    this.etPassValue = etPassValue;
    this.etpass = etpass;
    this.imageViewSource = imageViewSource;
    this.textView3 = textView3;
    this.textViewSigin = textViewSigin;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_login, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityLoginBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonLogin;
      Button buttonLogin = ViewBindings.findChildViewById(rootView, id);
      if (buttonLogin == null) {
        break missingId;
      }

      id = R.id.etEmail;
      TextInputLayout etEmail = ViewBindings.findChildViewById(rootView, id);
      if (etEmail == null) {
        break missingId;
      }

      id = R.id.etEmailValue;
      TextInputEditText etEmailValue = ViewBindings.findChildViewById(rootView, id);
      if (etEmailValue == null) {
        break missingId;
      }

      id = R.id.etPassValue;
      TextInputEditText etPassValue = ViewBindings.findChildViewById(rootView, id);
      if (etPassValue == null) {
        break missingId;
      }

      id = R.id.etpass;
      TextInputLayout etpass = ViewBindings.findChildViewById(rootView, id);
      if (etpass == null) {
        break missingId;
      }

      id = R.id.imageViewSource;
      ImageView imageViewSource = ViewBindings.findChildViewById(rootView, id);
      if (imageViewSource == null) {
        break missingId;
      }

      id = R.id.textView3;
      TextView textView3 = ViewBindings.findChildViewById(rootView, id);
      if (textView3 == null) {
        break missingId;
      }

      id = R.id.textViewSigin;
      TextView textViewSigin = ViewBindings.findChildViewById(rootView, id);
      if (textViewSigin == null) {
        break missingId;
      }

      return new ActivityLoginBinding((ConstraintLayout) rootView, buttonLogin, etEmail,
          etEmailValue, etPassValue, etpass, imageViewSource, textView3, textViewSigin);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
