// Generated by view binder compiler. Do not edit!
package com.rasika.nurturenectar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.rasika.nurturenectar.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityDonationDetailsBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button btnContact;

  @NonNull
  public final Button btnLocation;

  @NonNull
  public final TextView lblDate;

  @NonNull
  public final TextView lblName;

  @NonNull
  public final TextView lblPhone;

  @NonNull
  public final TextView lblPlace;

  @NonNull
  public final TextView lblRate;

  @NonNull
  public final TextView lblTotal;

  @NonNull
  public final TextView textView9;

  @NonNull
  public final TextView txtDate;

  @NonNull
  public final TextView txtName;

  @NonNull
  public final TextView txtPhone;

  @NonNull
  public final TextView txtPlace;

  @NonNull
  public final TextView txtRate;

  @NonNull
  public final TextView txtTotal;

  private ActivityDonationDetailsBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button btnContact, @NonNull Button btnLocation, @NonNull TextView lblDate,
      @NonNull TextView lblName, @NonNull TextView lblPhone, @NonNull TextView lblPlace,
      @NonNull TextView lblRate, @NonNull TextView lblTotal, @NonNull TextView textView9,
      @NonNull TextView txtDate, @NonNull TextView txtName, @NonNull TextView txtPhone,
      @NonNull TextView txtPlace, @NonNull TextView txtRate, @NonNull TextView txtTotal) {
    this.rootView = rootView;
    this.btnContact = btnContact;
    this.btnLocation = btnLocation;
    this.lblDate = lblDate;
    this.lblName = lblName;
    this.lblPhone = lblPhone;
    this.lblPlace = lblPlace;
    this.lblRate = lblRate;
    this.lblTotal = lblTotal;
    this.textView9 = textView9;
    this.txtDate = txtDate;
    this.txtName = txtName;
    this.txtPhone = txtPhone;
    this.txtPlace = txtPlace;
    this.txtRate = txtRate;
    this.txtTotal = txtTotal;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityDonationDetailsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityDonationDetailsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_donation_details, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityDonationDetailsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnContact;
      Button btnContact = ViewBindings.findChildViewById(rootView, id);
      if (btnContact == null) {
        break missingId;
      }

      id = R.id.btnLocation;
      Button btnLocation = ViewBindings.findChildViewById(rootView, id);
      if (btnLocation == null) {
        break missingId;
      }

      id = R.id.lblDate;
      TextView lblDate = ViewBindings.findChildViewById(rootView, id);
      if (lblDate == null) {
        break missingId;
      }

      id = R.id.lblName;
      TextView lblName = ViewBindings.findChildViewById(rootView, id);
      if (lblName == null) {
        break missingId;
      }

      id = R.id.lblPhone;
      TextView lblPhone = ViewBindings.findChildViewById(rootView, id);
      if (lblPhone == null) {
        break missingId;
      }

      id = R.id.lblPlace;
      TextView lblPlace = ViewBindings.findChildViewById(rootView, id);
      if (lblPlace == null) {
        break missingId;
      }

      id = R.id.lblRate;
      TextView lblRate = ViewBindings.findChildViewById(rootView, id);
      if (lblRate == null) {
        break missingId;
      }

      id = R.id.lblTotal;
      TextView lblTotal = ViewBindings.findChildViewById(rootView, id);
      if (lblTotal == null) {
        break missingId;
      }

      id = R.id.textView9;
      TextView textView9 = ViewBindings.findChildViewById(rootView, id);
      if (textView9 == null) {
        break missingId;
      }

      id = R.id.txtDate;
      TextView txtDate = ViewBindings.findChildViewById(rootView, id);
      if (txtDate == null) {
        break missingId;
      }

      id = R.id.txtName;
      TextView txtName = ViewBindings.findChildViewById(rootView, id);
      if (txtName == null) {
        break missingId;
      }

      id = R.id.txtPhone;
      TextView txtPhone = ViewBindings.findChildViewById(rootView, id);
      if (txtPhone == null) {
        break missingId;
      }

      id = R.id.txtPlace;
      TextView txtPlace = ViewBindings.findChildViewById(rootView, id);
      if (txtPlace == null) {
        break missingId;
      }

      id = R.id.txtRate;
      TextView txtRate = ViewBindings.findChildViewById(rootView, id);
      if (txtRate == null) {
        break missingId;
      }

      id = R.id.txtTotal;
      TextView txtTotal = ViewBindings.findChildViewById(rootView, id);
      if (txtTotal == null) {
        break missingId;
      }

      return new ActivityDonationDetailsBinding((ConstraintLayout) rootView, btnContact,
          btnLocation, lblDate, lblName, lblPhone, lblPlace, lblRate, lblTotal, textView9, txtDate,
          txtName, txtPhone, txtPlace, txtRate, txtTotal);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
