// Generated by view binder compiler. Do not edit!
package com.rasika.nurturenectar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import com.rasika.nurturenectar.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMilkDonationBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button buttonPost;

  @NonNull
  public final TextInputLayout etDate;

  @NonNull
  public final TextInputEditText etDateValue;

  @NonNull
  public final TextInputLayout etMilkPhone;

  @NonNull
  public final TextInputEditText etMilkPhoneValue;

  @NonNull
  public final TextInputLayout etMilkPlace;

  @NonNull
  public final TextInputEditText etMilkPlaceValue;

  @NonNull
  public final TextInputLayout etMilkRate;

  @NonNull
  public final TextInputEditText etMilkRateValue;

  @NonNull
  public final TextInputLayout etMilkTotalVolume;

  @NonNull
  public final TextInputEditText etMilkTotalVolumeValue;

  @NonNull
  public final RadioGroup radiGroupAllergies;

  @NonNull
  public final RadioGroup radiGroupDiseases;

  @NonNull
  public final RadioGroup radiGroupIllnesses;

  @NonNull
  public final RadioGroup radiGroupInfections;

  @NonNull
  public final RadioGroup radiGroupRate;

  @NonNull
  public final RadioButton radioButtonAllergiesNo;

  @NonNull
  public final RadioButton radioButtonAllergiesYes;

  @NonNull
  public final RadioButton radioButtonDiseasesNo;

  @NonNull
  public final RadioButton radioButtonDiseasesYes;

  @NonNull
  public final RadioButton radioButtonFree;

  @NonNull
  public final RadioButton radioButtonIllnessesNo;

  @NonNull
  public final RadioButton radioButtonIllnessesYes;

  @NonNull
  public final RadioButton radioButtonInfectionsNo;

  @NonNull
  public final RadioButton radioButtonInfectionsYes;

  @NonNull
  public final RadioButton radioButtonPaid;

  @NonNull
  public final TextView textView8;

  @NonNull
  public final TextView textViewAllergies;

  @NonNull
  public final TextView textViewDiseases;

  @NonNull
  public final TextView textViewIllnesses;

  @NonNull
  public final TextView textViewInfections;

  private ActivityMilkDonationBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button buttonPost, @NonNull TextInputLayout etDate,
      @NonNull TextInputEditText etDateValue, @NonNull TextInputLayout etMilkPhone,
      @NonNull TextInputEditText etMilkPhoneValue, @NonNull TextInputLayout etMilkPlace,
      @NonNull TextInputEditText etMilkPlaceValue, @NonNull TextInputLayout etMilkRate,
      @NonNull TextInputEditText etMilkRateValue, @NonNull TextInputLayout etMilkTotalVolume,
      @NonNull TextInputEditText etMilkTotalVolumeValue, @NonNull RadioGroup radiGroupAllergies,
      @NonNull RadioGroup radiGroupDiseases, @NonNull RadioGroup radiGroupIllnesses,
      @NonNull RadioGroup radiGroupInfections, @NonNull RadioGroup radiGroupRate,
      @NonNull RadioButton radioButtonAllergiesNo, @NonNull RadioButton radioButtonAllergiesYes,
      @NonNull RadioButton radioButtonDiseasesNo, @NonNull RadioButton radioButtonDiseasesYes,
      @NonNull RadioButton radioButtonFree, @NonNull RadioButton radioButtonIllnessesNo,
      @NonNull RadioButton radioButtonIllnessesYes, @NonNull RadioButton radioButtonInfectionsNo,
      @NonNull RadioButton radioButtonInfectionsYes, @NonNull RadioButton radioButtonPaid,
      @NonNull TextView textView8, @NonNull TextView textViewAllergies,
      @NonNull TextView textViewDiseases, @NonNull TextView textViewIllnesses,
      @NonNull TextView textViewInfections) {
    this.rootView = rootView;
    this.buttonPost = buttonPost;
    this.etDate = etDate;
    this.etDateValue = etDateValue;
    this.etMilkPhone = etMilkPhone;
    this.etMilkPhoneValue = etMilkPhoneValue;
    this.etMilkPlace = etMilkPlace;
    this.etMilkPlaceValue = etMilkPlaceValue;
    this.etMilkRate = etMilkRate;
    this.etMilkRateValue = etMilkRateValue;
    this.etMilkTotalVolume = etMilkTotalVolume;
    this.etMilkTotalVolumeValue = etMilkTotalVolumeValue;
    this.radiGroupAllergies = radiGroupAllergies;
    this.radiGroupDiseases = radiGroupDiseases;
    this.radiGroupIllnesses = radiGroupIllnesses;
    this.radiGroupInfections = radiGroupInfections;
    this.radiGroupRate = radiGroupRate;
    this.radioButtonAllergiesNo = radioButtonAllergiesNo;
    this.radioButtonAllergiesYes = radioButtonAllergiesYes;
    this.radioButtonDiseasesNo = radioButtonDiseasesNo;
    this.radioButtonDiseasesYes = radioButtonDiseasesYes;
    this.radioButtonFree = radioButtonFree;
    this.radioButtonIllnessesNo = radioButtonIllnessesNo;
    this.radioButtonIllnessesYes = radioButtonIllnessesYes;
    this.radioButtonInfectionsNo = radioButtonInfectionsNo;
    this.radioButtonInfectionsYes = radioButtonInfectionsYes;
    this.radioButtonPaid = radioButtonPaid;
    this.textView8 = textView8;
    this.textViewAllergies = textViewAllergies;
    this.textViewDiseases = textViewDiseases;
    this.textViewIllnesses = textViewIllnesses;
    this.textViewInfections = textViewInfections;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMilkDonationBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMilkDonationBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_milk_donation, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMilkDonationBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonPost;
      Button buttonPost = ViewBindings.findChildViewById(rootView, id);
      if (buttonPost == null) {
        break missingId;
      }

      id = R.id.etDate;
      TextInputLayout etDate = ViewBindings.findChildViewById(rootView, id);
      if (etDate == null) {
        break missingId;
      }

      id = R.id.etDateValue;
      TextInputEditText etDateValue = ViewBindings.findChildViewById(rootView, id);
      if (etDateValue == null) {
        break missingId;
      }

      id = R.id.etMilkPhone;
      TextInputLayout etMilkPhone = ViewBindings.findChildViewById(rootView, id);
      if (etMilkPhone == null) {
        break missingId;
      }

      id = R.id.etMilkPhoneValue;
      TextInputEditText etMilkPhoneValue = ViewBindings.findChildViewById(rootView, id);
      if (etMilkPhoneValue == null) {
        break missingId;
      }

      id = R.id.etMilkPlace;
      TextInputLayout etMilkPlace = ViewBindings.findChildViewById(rootView, id);
      if (etMilkPlace == null) {
        break missingId;
      }

      id = R.id.etMilkPlaceValue;
      TextInputEditText etMilkPlaceValue = ViewBindings.findChildViewById(rootView, id);
      if (etMilkPlaceValue == null) {
        break missingId;
      }

      id = R.id.etMilkRate;
      TextInputLayout etMilkRate = ViewBindings.findChildViewById(rootView, id);
      if (etMilkRate == null) {
        break missingId;
      }

      id = R.id.etMilkRateValue;
      TextInputEditText etMilkRateValue = ViewBindings.findChildViewById(rootView, id);
      if (etMilkRateValue == null) {
        break missingId;
      }

      id = R.id.etMilkTotalVolume;
      TextInputLayout etMilkTotalVolume = ViewBindings.findChildViewById(rootView, id);
      if (etMilkTotalVolume == null) {
        break missingId;
      }

      id = R.id.etMilkTotalVolumeValue;
      TextInputEditText etMilkTotalVolumeValue = ViewBindings.findChildViewById(rootView, id);
      if (etMilkTotalVolumeValue == null) {
        break missingId;
      }

      id = R.id.radiGroupAllergies;
      RadioGroup radiGroupAllergies = ViewBindings.findChildViewById(rootView, id);
      if (radiGroupAllergies == null) {
        break missingId;
      }

      id = R.id.radiGroupDiseases;
      RadioGroup radiGroupDiseases = ViewBindings.findChildViewById(rootView, id);
      if (radiGroupDiseases == null) {
        break missingId;
      }

      id = R.id.radiGroupIllnesses;
      RadioGroup radiGroupIllnesses = ViewBindings.findChildViewById(rootView, id);
      if (radiGroupIllnesses == null) {
        break missingId;
      }

      id = R.id.radiGroupInfections;
      RadioGroup radiGroupInfections = ViewBindings.findChildViewById(rootView, id);
      if (radiGroupInfections == null) {
        break missingId;
      }

      id = R.id.radiGroupRate;
      RadioGroup radiGroupRate = ViewBindings.findChildViewById(rootView, id);
      if (radiGroupRate == null) {
        break missingId;
      }

      id = R.id.radioButtonAllergiesNo;
      RadioButton radioButtonAllergiesNo = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonAllergiesNo == null) {
        break missingId;
      }

      id = R.id.radioButtonAllergiesYes;
      RadioButton radioButtonAllergiesYes = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonAllergiesYes == null) {
        break missingId;
      }

      id = R.id.radioButtonDiseasesNo;
      RadioButton radioButtonDiseasesNo = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonDiseasesNo == null) {
        break missingId;
      }

      id = R.id.radioButtonDiseasesYes;
      RadioButton radioButtonDiseasesYes = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonDiseasesYes == null) {
        break missingId;
      }

      id = R.id.radioButtonFree;
      RadioButton radioButtonFree = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonFree == null) {
        break missingId;
      }

      id = R.id.radioButtonIllnessesNo;
      RadioButton radioButtonIllnessesNo = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonIllnessesNo == null) {
        break missingId;
      }

      id = R.id.radioButtonIllnessesYes;
      RadioButton radioButtonIllnessesYes = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonIllnessesYes == null) {
        break missingId;
      }

      id = R.id.radioButtonInfectionsNo;
      RadioButton radioButtonInfectionsNo = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonInfectionsNo == null) {
        break missingId;
      }

      id = R.id.radioButtonInfectionsYes;
      RadioButton radioButtonInfectionsYes = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonInfectionsYes == null) {
        break missingId;
      }

      id = R.id.radioButtonPaid;
      RadioButton radioButtonPaid = ViewBindings.findChildViewById(rootView, id);
      if (radioButtonPaid == null) {
        break missingId;
      }

      id = R.id.textView8;
      TextView textView8 = ViewBindings.findChildViewById(rootView, id);
      if (textView8 == null) {
        break missingId;
      }

      id = R.id.textViewAllergies;
      TextView textViewAllergies = ViewBindings.findChildViewById(rootView, id);
      if (textViewAllergies == null) {
        break missingId;
      }

      id = R.id.textViewDiseases;
      TextView textViewDiseases = ViewBindings.findChildViewById(rootView, id);
      if (textViewDiseases == null) {
        break missingId;
      }

      id = R.id.textViewIllnesses;
      TextView textViewIllnesses = ViewBindings.findChildViewById(rootView, id);
      if (textViewIllnesses == null) {
        break missingId;
      }

      id = R.id.textViewInfections;
      TextView textViewInfections = ViewBindings.findChildViewById(rootView, id);
      if (textViewInfections == null) {
        break missingId;
      }

      return new ActivityMilkDonationBinding((ConstraintLayout) rootView, buttonPost, etDate,
          etDateValue, etMilkPhone, etMilkPhoneValue, etMilkPlace, etMilkPlaceValue, etMilkRate,
          etMilkRateValue, etMilkTotalVolume, etMilkTotalVolumeValue, radiGroupAllergies,
          radiGroupDiseases, radiGroupIllnesses, radiGroupInfections, radiGroupRate,
          radioButtonAllergiesNo, radioButtonAllergiesYes, radioButtonDiseasesNo,
          radioButtonDiseasesYes, radioButtonFree, radioButtonIllnessesNo, radioButtonIllnessesYes,
          radioButtonInfectionsNo, radioButtonInfectionsYes, radioButtonPaid, textView8,
          textViewAllergies, textViewDiseases, textViewIllnesses, textViewInfections);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
