// Generated by view binder compiler. Do not edit!
package com.rasika.nurturenectar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.rasika.nurturenectar.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class CardUserDonationBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ConstraintLayout constraintLayout2;

  @NonNull
  public final ImageView imageViewArrow;

  @NonNull
  public final TextView lblPostTime;

  @NonNull
  public final TextView textviewRate;

  @NonNull
  public final TextView textviewTotal;

  private CardUserDonationBinding(@NonNull ConstraintLayout rootView,
      @NonNull ConstraintLayout constraintLayout2, @NonNull ImageView imageViewArrow,
      @NonNull TextView lblPostTime, @NonNull TextView textviewRate,
      @NonNull TextView textviewTotal) {
    this.rootView = rootView;
    this.constraintLayout2 = constraintLayout2;
    this.imageViewArrow = imageViewArrow;
    this.lblPostTime = lblPostTime;
    this.textviewRate = textviewRate;
    this.textviewTotal = textviewTotal;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static CardUserDonationBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static CardUserDonationBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.card_user_donation, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static CardUserDonationBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.constraintLayout2;
      ConstraintLayout constraintLayout2 = ViewBindings.findChildViewById(rootView, id);
      if (constraintLayout2 == null) {
        break missingId;
      }

      id = R.id.imageViewArrow;
      ImageView imageViewArrow = ViewBindings.findChildViewById(rootView, id);
      if (imageViewArrow == null) {
        break missingId;
      }

      id = R.id.lblPostTime;
      TextView lblPostTime = ViewBindings.findChildViewById(rootView, id);
      if (lblPostTime == null) {
        break missingId;
      }

      id = R.id.textviewRate;
      TextView textviewRate = ViewBindings.findChildViewById(rootView, id);
      if (textviewRate == null) {
        break missingId;
      }

      id = R.id.textviewTotal;
      TextView textviewTotal = ViewBindings.findChildViewById(rootView, id);
      if (textviewTotal == null) {
        break missingId;
      }

      return new CardUserDonationBinding((ConstraintLayout) rootView, constraintLayout2,
          imageViewArrow, lblPostTime, textviewRate, textviewTotal);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
